# Generated by Django 2.2.7 on 2020-02-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('P', 'Publish'), ('D', 'Draft'), ('P', 'Pending')], max_length=1)),
            ],
        ),
    ]
