# Generated by Django 3.0.2 on 2020-02-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200203_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft'), ('Pending', 'Pending')], max_length=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
