# Generated by Django 3.0.2 on 2020-02-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Date',
        ),
    ]
