# Generated by Django 3.0.2 on 2020-02-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
