# Generated by Django 3.0.2 on 2020-02-04 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.OneToOneField(default= '1' , on_delete=django.db.models.deletion.CASCADE, to='blogs.Category', unique = False),
            preserve_default=False,
        ),
    ]
