# Generated by Django 3.0.2 on 2020-02-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20200204_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Term Insurance', 'Term Insurance'), ('Health Insurance', 'Health Insurance'), ('Travel Insurance', 'Travel Insurance'), ('Car Insurance', 'Car Insurance'), ('Bike Insurance', 'Bike Insurance'), ('Investment Plan', 'Investment Plan'), ('Other Blog', 'Other Blog')], default='', max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
