# Generated by Django 3.0.2 on 2020-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20200212_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Term Insurance', 'Term Insurance'), ('Health Insurance', 'Health Insurance'), ('Travel Insurance', 'Travel Insurance'), ('Car Insurance', 'Car Insurance'), ('Bike Insurance', 'Bike Insurance'), ('Investment Plan', 'Investment Plan'), ('Child Plan', 'Child Plan'), ('Other Blog', 'Other Blog')], max_length=25),
        ),
    ]
