# Generated by Django 3.0.2 on 2020-02-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_auto_20200212_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogs.Category'),
        ),
    ]
