# Generated by Django 3.0.2 on 2020-02-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_auto_20200212_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='images/Desert.jpg', null=True, upload_to='images/'),
        ),
    ]
