# Generated by Django 3.0.2 on 2020-02-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_auto_20200213_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='images/docslogo.png', null=True, upload_to='images/'),
        ),
    ]
