# Generated by Django 3.0.2 on 2020-02-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0032_auto_20200213_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('contact_no', models.IntegerField(blank=True)),
                ('service', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
