# Generated by Django 3.0.2 on 2020-02-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0033_enquiries'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiries',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
