# Generated by Django 3.0.2 on 2020-02-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0034_enquiries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
