# Generated by Django 3.0.2 on 2020-02-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0035_auto_20200214_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
